import { AboutProgramCardProps } from "../../../Components/Shared/AboutProgramCard/types";
import RouseHonorBand2324 from "../../../assets/images/20232024RouseHonorBand.jpeg";

export const rousePreviousBandInfo: AboutProgramCardProps = {
  programName: "2023-2024 Rouse Honor Band",
  programInfo: `Thank you! Your contributions to our program continue to shine through the band program in so many ways. Your hard work and dedication were the impetus for this performance today. We miss you!`,
  imgSrc: RouseHonorBand2324,
  roster: [
    "Student 1",
    "Student 2",
    "Student 3",
    "Student 4",
    "Student 5",
    "Student 6",
    "Student 7",
    "Student 8",
    "Student 9",
    "Student 10",
    "Student 11",
    "Student 12",
    "Student 13",
    "Student 14",
    "Student 15",
    "Student 16",
    "Student 17",
    "Student 18",
    "Student 19",
    "Student 20",
    "Student 21",
    "Student 22",
    "Student 23",
    "Student 24",
    "Student 25",
    "Student 26",
    "Student 27",
    "Student 28",
    "Student 29",
    "Student 30",
    "Student 31",
    "Student 32",
    "Student 33",
    "Student 34",
    "Student 35",
    "Student 36",
    "Student 37",
    "Student 38",
    "Student 39",
    "Student 40",
    "Student 41",
    "Student 42",
    "Student 43",
    "Student 44",
    "Student 45",
    "Student 46",
    "Student 47",
  ],
};
