import { AboutProgramCardProps } from "../../../Components/Shared/AboutProgramCard/types";
import RouseHonorBand2324 from "../../../assets/images/20232024RouseHonorBand.jpeg";

export const rousePreviousBandInfo: AboutProgramCardProps = {
  programName: "2023-2024 Rouse Honor Band",
  programInfo: `Thank you! Your contributions to our program continue to shine through the band program in so many ways. Your hard work and dedication were the impetus for this performance today. We miss you!`,
  imgSrc: RouseHonorBand2324,
  roster: [
    "Claire Allen",
    "Lucy Allison",
    "Mason Azios",
    "Ash Beard",
    "Morgan Berkley",
    "Chris Bishop",
    "Mackenzie Blackstock",
    "Isabella Burg",
    "Noah Carillo",
    "Hasini Chandrakumar",
    "Charlotte Chen",
    "Sofia Corneille",
    "Broderick Corneille",
    "Reece Cowan",
    "Chloe Cumberledge",
    "William Davis",
    "Chase Fontenot",
    "Carson Frank",
    "Mercedes Gomez",
    "Maanas Gondipalli",
    "Charlie Grandstaff",
    "Rebekah Hall",
    "Angelica Hernandez-Garcia",
    "Andrew Huber",
    "Chad Johnson",
    "Simon King",
    "Siddhant Lakhani",
    "Huckleberry LayPort",
    "Aditya Lingam",
    "Emma Logan",
    "Abraham Ly",
    "JC Martinez",
    "Logan Matic",
    "Logan McKee",
    "Lincoln Miller",
    "Kent O'Pella",
    "Megan Peterson",
    "Maria Pitts",
    "Noah Powell",
    "Emerson Scott",
    "Chase Skemp",
    "Sophie Summers",
    "Jacob Troller",
    "Jacobo Velez",
    "Logan Washam",
    "Cutter Williams",
    "Renushri Yannam",
  ],
};
