import { AboutProgramCardProps } from "../../../Components/Shared/AboutProgramCard/types";
import PreviousYearBand from "../../../assets/images/2324WMSWE.jpeg";

export const wileyPreviousBandInfo: AboutProgramCardProps = {
  programName: "2023-2024 Wiley Wind Ensemble",
  programInfo: `Thank you to the incredible musicians of the 2023-2024 Wiley Wind Ensemble for their hard work and dedication to our program. Your efforts and musicianship are what made today’s performance a reality. We are forever grateful for you and all you have done to leave your mark on our program!`,
  imgSrc: PreviousYearBand,
  roster: [
    "Kasey Actkinson",
    "Kenley Actkinson",
    "Destinee Allen",
    "Tamara Amezquita Alaniz",
    "Abbey Carter",
    "Grace Carter",
    "Madoline Chambers",
    "Lia Cooper",
    "Carter Copeland",
    "Ajay Dev",
    "Kristofer Espino",
    "Nolan Fritsch",
    "Madyson Gilstrap",
    "Samantha Glenn",
    "Alexander Graham",
    "Jacob Guzman",
    "Dana Han",
    "Hogeon Han",
    "Zayden Hill",
    "Lela Hitchcock",
    "Jackson Hull",
    "Elliot King",
    "Jesse Lewis",
    "Emma Love",
    "Lauren Mesa",
    "Isabela Moreno",
    "Sanaika Nandigam",
    "Ashlynn Newby",
    "Oliver Newell",
    "Elan Perez",
    "Noah Pettit",
    "John Powell",
    "Ashwath Purushothaman",
    "Jacob Reardon",
    "Reese Roaquin",
    "Joseph Robb",
    "Haeryn Roh",
    "Joshua Romriell",
    "Joseph Schmitt",
    "Molly Schwartz",
    "Niron Shrestha",
    "Dylan Siegel",
    "Austin Smith",
    "Caden Stanfield",
    "Isaac Stoddard",
    "Connor Tackett",
    "Marin Tanteri",
    "Ashley Taubert",
    "Micah Thompson",
    "Kaitlyn Toney",
    "Tatum Valenzuela",
    "Luke Wallis",
    "Claire Winchell",
    "Ethan Wood",
    "Yaryna Zakharko",
  ],
};
