import { AboutProgramCardProps } from "../../../Components/Shared/AboutProgramCard/types";
import PreviousYearBand from "../../../assets/images/2324WMSWE.jpeg";

export const wileyPreviousBandInfo: AboutProgramCardProps = {
  programName: "2023-2024 Wiley Wind Ensemble",
  programInfo: `Thank you to the incredible musicians of the 2023-2024 Wiley Wind Ensemble for their hard work and dedication to our program. Your efforts and musicianship are what made today’s performance a reality. We are forever grateful for you and all you have done to leave your mark on our program!`,
  imgSrc: PreviousYearBand,
  roster: [
    "Student 1",
    "Student 2",
    "Student 3",
    "Student 4",
    "Student 5",
    "Student 6",
    "Student 7",
    "Student 8",
    "Student 9",
    "Student 10",
    "Student 11",
    "Student 12",
    "Student 13",
    "Student 14",
    "Student 15",
    "Student 16",
    "Student 17",
    "Student 18",
    "Student 19",
    "Student 20",
    "Student 21",
    "Student 22",
    "Student 23",
    "Student 24",
    "Student 25",
    "Student 26",
    "Student 27",
    "Student 28",
    "Student 29",
    "Student 30",
    "Student 31",
    "Student 32",
    "Student 33",
    "Student 34",
    "Student 35",
    "Student 36",
    "Student 37",
    "Student 38",
    "Student 39",
    "Student 40",
    "Student 41",
    "Student 42",
    "Student 43",
    "Student 44",
    "Student 45",
    "Student 46",
    "Student 47",
    "Student 48",
    "Student 49",
    "Student 50",
    "Student 51",
    "Student 52",
    "Student 53",
    "Student 54",
    "Student 55",
  ],
};
